version: "3.3"
services:
  
  sgpdbuser:
      image: postgres:latest
      restart: always
      env_file: ./configuser/dbuser.env
      ports: 
        - "5434:5434"
      volumes:
            - ./configuser:/docker-entrypoint-initdb.d
      command: -p 5434
      networks:
        - dockercompose
      healthcheck:
            test: ["CMD-SHELL", "pg_isready"]
            interval: 10s
            timeout: 5s
            retries: 5

volumes: {}
networks:
  dockercompose: